//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:8</p>
  /// </summary>
  public class AsmViewerModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public void Show() => _Show.Fire();
    [NotNull] public IViewableProperty<bool> IsVisible => _IsVisible;
    [NotNull] public IViewableProperty<bool> IsLoading => _IsLoading;
    [NotNull] public IViewableProperty<string> UnavailabilityReason => _UnavailabilityReason;
    [NotNull] public IViewableProperty<string> ErrorCode => _ErrorCode;
    [NotNull] public IViewableProperty<string> CurrentContent => _CurrentContent;
    [NotNull] public IViewableProperty<string> SourceFilePath => _SourceFilePath;
    [NotNull] public IViewableProperty<int?> CaretOffset => _CaretOffset;
    [NotNull] public IViewableProperty<long?> DocumentModificationStamp => _DocumentModificationStamp;
    [NotNull] public IViewableProperty<string> SnapshotContent => _SnapshotContent;
    [NotNull] public IViewableProperty<bool> HasSnapshot => _HasSnapshot;
    [NotNull] public IViewableProperty<bool> ShowAsmComments => _ShowAsmComments;
    [NotNull] public IViewableProperty<bool> UseTieredJit => _UseTieredJit;
    [NotNull] public IViewableProperty<bool> UsePGO => _UsePGO;
    [NotNull] public IViewableProperty<bool> Diffable => _Diffable;
    [NotNull] public IViewableProperty<bool> RunAppMode => _RunAppMode;
    [NotNull] public IViewableProperty<bool> UseNoRestoreFlag => _UseNoRestoreFlag;
    [NotNull] public IViewableProperty<bool> UseDotnetPublishForReload => _UseDotnetPublishForReload;
    [NotNull] public IViewableProperty<bool> UseDotnetBuildForReload => _UseDotnetBuildForReload;
    [NotNull] public IViewableProperty<bool> UseUnloadableContext => _UseUnloadableContext;
    [NotNull] public IViewableProperty<bool> DontGuessTFM => _DontGuessTFM;
    [NotNull] public IViewableProperty<string> SelectedCustomJit => _SelectedCustomJit;
    
    //private fields
    [NotNull] private readonly RdSignal<Unit> _Show;
    [NotNull] private readonly RdProperty<bool> _IsVisible;
    [NotNull] private readonly RdProperty<bool> _IsLoading;
    [NotNull] private readonly RdProperty<string> _UnavailabilityReason;
    [NotNull] private readonly RdProperty<string> _ErrorCode;
    [NotNull] private readonly RdProperty<string> _CurrentContent;
    [NotNull] private readonly RdProperty<string> _SourceFilePath;
    [NotNull] private readonly RdProperty<int?> _CaretOffset;
    [NotNull] private readonly RdProperty<long?> _DocumentModificationStamp;
    [NotNull] private readonly RdProperty<string> _SnapshotContent;
    [NotNull] private readonly RdProperty<bool> _HasSnapshot;
    [NotNull] private readonly RdProperty<bool> _ShowAsmComments;
    [NotNull] private readonly RdProperty<bool> _UseTieredJit;
    [NotNull] private readonly RdProperty<bool> _UsePGO;
    [NotNull] private readonly RdProperty<bool> _Diffable;
    [NotNull] private readonly RdProperty<bool> _RunAppMode;
    [NotNull] private readonly RdProperty<bool> _UseNoRestoreFlag;
    [NotNull] private readonly RdProperty<bool> _UseDotnetPublishForReload;
    [NotNull] private readonly RdProperty<bool> _UseDotnetBuildForReload;
    [NotNull] private readonly RdProperty<bool> _UseUnloadableContext;
    [NotNull] private readonly RdProperty<bool> _DontGuessTFM;
    [NotNull] private readonly RdProperty<string> _SelectedCustomJit;
    
    //primary constructor
    private AsmViewerModel(
      [NotNull] RdSignal<Unit> show,
      [NotNull] RdProperty<bool> isVisible,
      [NotNull] RdProperty<bool> isLoading,
      [NotNull] RdProperty<string> unavailabilityReason,
      [NotNull] RdProperty<string> errorCode,
      [NotNull] RdProperty<string> currentContent,
      [NotNull] RdProperty<string> sourceFilePath,
      [NotNull] RdProperty<int?> caretOffset,
      [NotNull] RdProperty<long?> documentModificationStamp,
      [NotNull] RdProperty<string> snapshotContent,
      [NotNull] RdProperty<bool> hasSnapshot,
      [NotNull] RdProperty<bool> showAsmComments,
      [NotNull] RdProperty<bool> useTieredJit,
      [NotNull] RdProperty<bool> usePGO,
      [NotNull] RdProperty<bool> diffable,
      [NotNull] RdProperty<bool> runAppMode,
      [NotNull] RdProperty<bool> useNoRestoreFlag,
      [NotNull] RdProperty<bool> useDotnetPublishForReload,
      [NotNull] RdProperty<bool> useDotnetBuildForReload,
      [NotNull] RdProperty<bool> useUnloadableContext,
      [NotNull] RdProperty<bool> dontGuessTFM,
      [NotNull] RdProperty<string> selectedCustomJit
    )
    {
      if (show == null) throw new ArgumentNullException("show");
      if (isVisible == null) throw new ArgumentNullException("isVisible");
      if (isLoading == null) throw new ArgumentNullException("isLoading");
      if (unavailabilityReason == null) throw new ArgumentNullException("unavailabilityReason");
      if (errorCode == null) throw new ArgumentNullException("errorCode");
      if (currentContent == null) throw new ArgumentNullException("currentContent");
      if (sourceFilePath == null) throw new ArgumentNullException("sourceFilePath");
      if (caretOffset == null) throw new ArgumentNullException("caretOffset");
      if (documentModificationStamp == null) throw new ArgumentNullException("documentModificationStamp");
      if (snapshotContent == null) throw new ArgumentNullException("snapshotContent");
      if (hasSnapshot == null) throw new ArgumentNullException("hasSnapshot");
      if (showAsmComments == null) throw new ArgumentNullException("showAsmComments");
      if (useTieredJit == null) throw new ArgumentNullException("useTieredJit");
      if (usePGO == null) throw new ArgumentNullException("usePGO");
      if (diffable == null) throw new ArgumentNullException("diffable");
      if (runAppMode == null) throw new ArgumentNullException("runAppMode");
      if (useNoRestoreFlag == null) throw new ArgumentNullException("useNoRestoreFlag");
      if (useDotnetPublishForReload == null) throw new ArgumentNullException("useDotnetPublishForReload");
      if (useDotnetBuildForReload == null) throw new ArgumentNullException("useDotnetBuildForReload");
      if (useUnloadableContext == null) throw new ArgumentNullException("useUnloadableContext");
      if (dontGuessTFM == null) throw new ArgumentNullException("dontGuessTFM");
      if (selectedCustomJit == null) throw new ArgumentNullException("selectedCustomJit");
      
      _Show = show;
      _IsVisible = isVisible;
      _IsLoading = isLoading;
      _UnavailabilityReason = unavailabilityReason;
      _ErrorCode = errorCode;
      _CurrentContent = currentContent;
      _SourceFilePath = sourceFilePath;
      _CaretOffset = caretOffset;
      _DocumentModificationStamp = documentModificationStamp;
      _SnapshotContent = snapshotContent;
      _HasSnapshot = hasSnapshot;
      _ShowAsmComments = showAsmComments;
      _UseTieredJit = useTieredJit;
      _UsePGO = usePGO;
      _Diffable = diffable;
      _RunAppMode = runAppMode;
      _UseNoRestoreFlag = useNoRestoreFlag;
      _UseDotnetPublishForReload = useDotnetPublishForReload;
      _UseDotnetBuildForReload = useDotnetBuildForReload;
      _UseUnloadableContext = useUnloadableContext;
      _DontGuessTFM = dontGuessTFM;
      _SelectedCustomJit = selectedCustomJit;
      _IsVisible.OptimizeNested = true;
      _IsLoading.OptimizeNested = true;
      _UnavailabilityReason.OptimizeNested = true;
      _ErrorCode.OptimizeNested = true;
      _CurrentContent.OptimizeNested = true;
      _SourceFilePath.OptimizeNested = true;
      _CaretOffset.OptimizeNested = true;
      _DocumentModificationStamp.OptimizeNested = true;
      _SnapshotContent.OptimizeNested = true;
      _HasSnapshot.OptimizeNested = true;
      _ShowAsmComments.OptimizeNested = true;
      _UseTieredJit.OptimizeNested = true;
      _UsePGO.OptimizeNested = true;
      _Diffable.OptimizeNested = true;
      _RunAppMode.OptimizeNested = true;
      _UseNoRestoreFlag.OptimizeNested = true;
      _UseDotnetPublishForReload.OptimizeNested = true;
      _UseDotnetBuildForReload.OptimizeNested = true;
      _UseUnloadableContext.OptimizeNested = true;
      _DontGuessTFM.OptimizeNested = true;
      _SelectedCustomJit.OptimizeNested = true;
      _UnavailabilityReason.ValueCanBeNull = true;
      _ErrorCode.ValueCanBeNull = true;
      _CurrentContent.ValueCanBeNull = true;
      _SourceFilePath.ValueCanBeNull = true;
      _CaretOffset.ValueCanBeNull = true;
      _DocumentModificationStamp.ValueCanBeNull = true;
      _SnapshotContent.ValueCanBeNull = true;
      _SelectedCustomJit.ValueCanBeNull = true;
      BindableChildren.Add(new KeyValuePair<string, object>("show", _Show));
      BindableChildren.Add(new KeyValuePair<string, object>("isVisible", _IsVisible));
      BindableChildren.Add(new KeyValuePair<string, object>("isLoading", _IsLoading));
      BindableChildren.Add(new KeyValuePair<string, object>("unavailabilityReason", _UnavailabilityReason));
      BindableChildren.Add(new KeyValuePair<string, object>("errorCode", _ErrorCode));
      BindableChildren.Add(new KeyValuePair<string, object>("currentContent", _CurrentContent));
      BindableChildren.Add(new KeyValuePair<string, object>("sourceFilePath", _SourceFilePath));
      BindableChildren.Add(new KeyValuePair<string, object>("caretOffset", _CaretOffset));
      BindableChildren.Add(new KeyValuePair<string, object>("documentModificationStamp", _DocumentModificationStamp));
      BindableChildren.Add(new KeyValuePair<string, object>("snapshotContent", _SnapshotContent));
      BindableChildren.Add(new KeyValuePair<string, object>("hasSnapshot", _HasSnapshot));
      BindableChildren.Add(new KeyValuePair<string, object>("showAsmComments", _ShowAsmComments));
      BindableChildren.Add(new KeyValuePair<string, object>("useTieredJit", _UseTieredJit));
      BindableChildren.Add(new KeyValuePair<string, object>("usePGO", _UsePGO));
      BindableChildren.Add(new KeyValuePair<string, object>("diffable", _Diffable));
      BindableChildren.Add(new KeyValuePair<string, object>("runAppMode", _RunAppMode));
      BindableChildren.Add(new KeyValuePair<string, object>("useNoRestoreFlag", _UseNoRestoreFlag));
      BindableChildren.Add(new KeyValuePair<string, object>("useDotnetPublishForReload", _UseDotnetPublishForReload));
      BindableChildren.Add(new KeyValuePair<string, object>("useDotnetBuildForReload", _UseDotnetBuildForReload));
      BindableChildren.Add(new KeyValuePair<string, object>("useUnloadableContext", _UseUnloadableContext));
      BindableChildren.Add(new KeyValuePair<string, object>("dontGuessTFM", _DontGuessTFM));
      BindableChildren.Add(new KeyValuePair<string, object>("selectedCustomJit", _SelectedCustomJit));
    }
    //secondary constructor
    internal AsmViewerModel (
    ) : this (
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdProperty<int?>(ReadIntNullable, WriteIntNullable),
      new RdProperty<long?>(ReadLongNullable, WriteLongNullable),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<int?> ReadIntNullable = JetBrains.Rd.Impl.Serializers.ReadInt.NullableStruct();
    public static CtxReadDelegate<long?> ReadLongNullable = JetBrains.Rd.Impl.Serializers.ReadLong.NullableStruct();
    
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<int?> WriteIntNullable = JetBrains.Rd.Impl.Serializers.WriteInt.NullableStruct();
    public static  CtxWriteDelegate<long?> WriteLongNullable = JetBrains.Rd.Impl.Serializers.WriteLong.NullableStruct();
    
    protected override long SerializationHash => 8782978450809573702L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("AsmViewerModel (");
      using (printer.IndentCookie()) {
        printer.Print("show = "); _Show.PrintEx(printer); printer.Println();
        printer.Print("isVisible = "); _IsVisible.PrintEx(printer); printer.Println();
        printer.Print("isLoading = "); _IsLoading.PrintEx(printer); printer.Println();
        printer.Print("unavailabilityReason = "); _UnavailabilityReason.PrintEx(printer); printer.Println();
        printer.Print("errorCode = "); _ErrorCode.PrintEx(printer); printer.Println();
        printer.Print("currentContent = "); _CurrentContent.PrintEx(printer); printer.Println();
        printer.Print("sourceFilePath = "); _SourceFilePath.PrintEx(printer); printer.Println();
        printer.Print("caretOffset = "); _CaretOffset.PrintEx(printer); printer.Println();
        printer.Print("documentModificationStamp = "); _DocumentModificationStamp.PrintEx(printer); printer.Println();
        printer.Print("snapshotContent = "); _SnapshotContent.PrintEx(printer); printer.Println();
        printer.Print("hasSnapshot = "); _HasSnapshot.PrintEx(printer); printer.Println();
        printer.Print("showAsmComments = "); _ShowAsmComments.PrintEx(printer); printer.Println();
        printer.Print("useTieredJit = "); _UseTieredJit.PrintEx(printer); printer.Println();
        printer.Print("usePGO = "); _UsePGO.PrintEx(printer); printer.Println();
        printer.Print("diffable = "); _Diffable.PrintEx(printer); printer.Println();
        printer.Print("runAppMode = "); _RunAppMode.PrintEx(printer); printer.Println();
        printer.Print("useNoRestoreFlag = "); _UseNoRestoreFlag.PrintEx(printer); printer.Println();
        printer.Print("useDotnetPublishForReload = "); _UseDotnetPublishForReload.PrintEx(printer); printer.Println();
        printer.Print("useDotnetBuildForReload = "); _UseDotnetBuildForReload.PrintEx(printer); printer.Println();
        printer.Print("useUnloadableContext = "); _UseUnloadableContext.PrintEx(printer); printer.Println();
        printer.Print("dontGuessTFM = "); _DontGuessTFM.PrintEx(printer); printer.Println();
        printer.Print("selectedCustomJit = "); _SelectedCustomJit.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionAsmViewerModelEx
   {
    public static AsmViewerModel GetAsmViewerModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("asmViewerModel", () => new AsmViewerModel());
    }
  }
}
