//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:8</p>
  /// </summary>
  public class AsmViewerModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public void Show() => _Show.Fire();
    [NotNull] public IViewableProperty<bool> IsVisible => _IsVisible;
    [NotNull] public IViewableProperty<bool> IsLoading => _IsLoading;
    [NotNull] public IRdEndpoint<CompileRequest, CompilationResponse> Compile => _Compile;
    
    //private fields
    [NotNull] private readonly RdSignal<Unit> _Show;
    [NotNull] private readonly RdProperty<bool> _IsVisible;
    [NotNull] private readonly RdProperty<bool> _IsLoading;
    [NotNull] private readonly RdCall<CompileRequest, CompilationResponse> _Compile;
    
    //primary constructor
    private AsmViewerModel(
      [NotNull] RdSignal<Unit> show,
      [NotNull] RdProperty<bool> isVisible,
      [NotNull] RdProperty<bool> isLoading,
      [NotNull] RdCall<CompileRequest, CompilationResponse> compile
    )
    {
      if (show == null) throw new ArgumentNullException("show");
      if (isVisible == null) throw new ArgumentNullException("isVisible");
      if (isLoading == null) throw new ArgumentNullException("isLoading");
      if (compile == null) throw new ArgumentNullException("compile");
      
      _Show = show;
      _IsVisible = isVisible;
      _IsLoading = isLoading;
      _Compile = compile;
      _IsVisible.OptimizeNested = true;
      _IsLoading.OptimizeNested = true;
      BindableChildren.Add(new KeyValuePair<string, object>("show", _Show));
      BindableChildren.Add(new KeyValuePair<string, object>("isVisible", _IsVisible));
      BindableChildren.Add(new KeyValuePair<string, object>("isLoading", _IsLoading));
      BindableChildren.Add(new KeyValuePair<string, object>("compile", _Compile));
    }
    //secondary constructor
    internal AsmViewerModel (
    ) : this (
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdCall<CompileRequest, CompilationResponse>(CompileRequest.Read, CompileRequest.Write, CompilationResponse.Read, CompilationResponse.Write)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => -9119311762756942617L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("AsmViewerModel (");
      using (printer.IndentCookie()) {
        printer.Print("show = "); _Show.PrintEx(printer); printer.Println();
        printer.Print("isVisible = "); _IsVisible.PrintEx(printer); printer.Println();
        printer.Print("isLoading = "); _IsLoading.PrintEx(printer); printer.Println();
        printer.Print("compile = "); _Compile.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionAsmViewerModelEx
   {
    public static AsmViewerModel GetAsmViewerModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("asmViewerModel", () => new AsmViewerModel());
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:48</p>
  /// </summary>
  public sealed class CaretPosition : IPrintable, IEquatable<CaretPosition>
  {
    //fields
    //public fields
    [NotNull] public string FilePath {get; private set;}
    public long FileStamp {get; private set;}
    public int Offset {get; private set;}
    
    //private fields
    //primary constructor
    public CaretPosition(
      [NotNull] string filePath,
      long fileStamp,
      int offset
    )
    {
      if (filePath == null) throw new ArgumentNullException("filePath");
      
      FilePath = filePath;
      FileStamp = fileStamp;
      Offset = offset;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out string filePath, out long fileStamp, out int offset)
    {
      filePath = FilePath;
      fileStamp = FileStamp;
      offset = Offset;
    }
    //statics
    
    public static CtxReadDelegate<CaretPosition> Read = (ctx, reader) => 
    {
      var filePath = reader.ReadString();
      var fileStamp = reader.ReadLong();
      var offset = reader.ReadInt();
      var _result = new CaretPosition(filePath, fileStamp, offset);
      return _result;
    };
    
    public static CtxWriteDelegate<CaretPosition> Write = (ctx, writer, value) => 
    {
      writer.Write(value.FilePath);
      writer.Write(value.FileStamp);
      writer.Write(value.Offset);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((CaretPosition) obj);
    }
    public bool Equals(CaretPosition other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return FilePath == other.FilePath && FileStamp == other.FileStamp && Offset == other.Offset;
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + FilePath.GetHashCode();
        hash = hash * 31 + FileStamp.GetHashCode();
        hash = hash * 31 + Offset.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("CaretPosition (");
      using (printer.IndentCookie()) {
        printer.Print("filePath = "); FilePath.PrintEx(printer); printer.Println();
        printer.Print("fileStamp = "); FileStamp.PrintEx(printer); printer.Println();
        printer.Print("offset = "); Offset.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:73</p>
  /// </summary>
  public sealed class CompilationResponse : IPrintable, IEquatable<CompilationResponse>
  {
    //fields
    //public fields
    [CanBeNull] public string Content {get; private set;}
    [CanBeNull] public ErrorInfo Error {get; private set;}
    
    //private fields
    //primary constructor
    public CompilationResponse(
      [CanBeNull] string content,
      [CanBeNull] ErrorInfo error
    )
    {
      Content = content;
      Error = error;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([CanBeNull] out string content, [CanBeNull] out ErrorInfo error)
    {
      content = Content;
      error = Error;
    }
    //statics
    
    public static CtxReadDelegate<CompilationResponse> Read = (ctx, reader) => 
    {
      var content = ReadStringNullable(ctx, reader);
      var error = ReadErrorInfoNullable(ctx, reader);
      var _result = new CompilationResponse(content, error);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<ErrorInfo> ReadErrorInfoNullable = ErrorInfo.Read.NullableClass();
    
    public static CtxWriteDelegate<CompilationResponse> Write = (ctx, writer, value) => 
    {
      WriteStringNullable(ctx, writer, value.Content);
      WriteErrorInfoNullable(ctx, writer, value.Error);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<ErrorInfo> WriteErrorInfoNullable = ErrorInfo.Write.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((CompilationResponse) obj);
    }
    public bool Equals(CompilationResponse other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(Content, other.Content) && Equals(Error, other.Error);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + (Content != null ? Content.GetHashCode() : 0);
        hash = hash * 31 + (Error != null ? Error.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("CompilationResponse (");
      using (printer.IndentCookie()) {
        printer.Print("content = "); Content.PrintEx(printer); printer.Println();
        printer.Print("error = "); Error.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:68</p>
  /// </summary>
  public sealed class CompileRequest : IPrintable, IEquatable<CompileRequest>
  {
    //fields
    //public fields
    [NotNull] public JetBrains.Rider.Model.CaretPosition CaretPosition {get; private set;}
    [NotNull] public JitConfiguration Configuration {get; private set;}
    
    //private fields
    //primary constructor
    public CompileRequest(
      [NotNull] JetBrains.Rider.Model.CaretPosition caretPosition,
      [NotNull] JitConfiguration configuration
    )
    {
      if (caretPosition == null) throw new ArgumentNullException("caretPosition");
      if (configuration == null) throw new ArgumentNullException("configuration");
      
      CaretPosition = caretPosition;
      Configuration = configuration;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct([NotNull] out JetBrains.Rider.Model.CaretPosition caretPosition, [NotNull] out JitConfiguration configuration)
    {
      caretPosition = CaretPosition;
      configuration = Configuration;
    }
    //statics
    
    public static CtxReadDelegate<CompileRequest> Read = (ctx, reader) => 
    {
      var caretPosition = JetBrains.Rider.Model.CaretPosition.Read(ctx, reader);
      var configuration = JitConfiguration.Read(ctx, reader);
      var _result = new CompileRequest(caretPosition, configuration);
      return _result;
    };
    
    public static CtxWriteDelegate<CompileRequest> Write = (ctx, writer, value) => 
    {
      JetBrains.Rider.Model.CaretPosition.Write(ctx, writer, value.CaretPosition);
      JitConfiguration.Write(ctx, writer, value.Configuration);
    };
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((CompileRequest) obj);
    }
    public bool Equals(CompileRequest other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Equals(CaretPosition, other.CaretPosition) && Equals(Configuration, other.Configuration);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + CaretPosition.GetHashCode();
        hash = hash * 31 + Configuration.GetHashCode();
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("CompileRequest (");
      using (printer.IndentCookie()) {
        printer.Print("caretPosition = "); CaretPosition.PrintEx(printer); printer.Println();
        printer.Print("configuration = "); Configuration.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:10</p>
  /// </summary>
  public enum ErrorCode {
    SourceFileNotFound,
    PsiSourceFileUnavailable,
    UnsupportedLanguage,
    InvalidCaretPosition,
    PgoNotSupportedForAot,
    RunModeNotSupportedForAot,
    TieredJitNotSupportedForAot,
    FlowgraphsNotSupportedForAot,
    FlowgraphsForClassNotSupported,
    UnsupportedTargetFramework,
    CustomRuntimeRequiresNet7,
    DisassemblyTargetNotFound,
    CompilationFailed,
    ProjectPathNotFound,
    DotnetBuildFailed,
    DotnetPublishFailed,
    RuntimePackNotFound,
    CoreClrCheckedNotFound,
    ClrJitNotFound,
    UpdateCancelled,
    UnknownError
  }
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:43</p>
  /// </summary>
  public sealed class ErrorInfo : IPrintable, IEquatable<ErrorInfo>
  {
    //fields
    //public fields
    public ErrorCode Code {get; private set;}
    [CanBeNull] public string Details {get; private set;}
    
    //private fields
    //primary constructor
    public ErrorInfo(
      ErrorCode code,
      [CanBeNull] string details
    )
    {
      Code = code;
      Details = details;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out ErrorCode code, [CanBeNull] out string details)
    {
      code = Code;
      details = Details;
    }
    //statics
    
    public static CtxReadDelegate<ErrorInfo> Read = (ctx, reader) => 
    {
      var code = (ErrorCode)reader.ReadInt();
      var details = ReadStringNullable(ctx, reader);
      var _result = new ErrorInfo(code, details);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<ErrorInfo> Write = (ctx, writer, value) => 
    {
      writer.Write((int)value.Code);
      WriteStringNullable(ctx, writer, value.Details);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((ErrorInfo) obj);
    }
    public bool Equals(ErrorInfo other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return Code == other.Code && Equals(Details, other.Details);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + (int) Code;
        hash = hash * 31 + (Details != null ? Details.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("ErrorInfo (");
      using (printer.IndentCookie()) {
        printer.Print("code = "); Code.PrintEx(printer); printer.Println();
        printer.Print("details = "); Details.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: AsmViewerModel.kt:54</p>
  /// </summary>
  public sealed class JitConfiguration : IPrintable, IEquatable<JitConfiguration>
  {
    //fields
    //public fields
    public bool ShowAsmComments {get; private set;}
    public bool Diffable {get; private set;}
    public bool UseTieredJit {get; private set;}
    public bool UsePGO {get; private set;}
    public bool RunAppMode {get; private set;}
    public bool UseNoRestoreFlag {get; private set;}
    public bool UseDotnetPublishForReload {get; private set;}
    public bool UseDotnetBuildForReload {get; private set;}
    public bool UseUnloadableContext {get; private set;}
    public bool DontGuessTFM {get; private set;}
    [CanBeNull] public string SelectedCustomJit {get; private set;}
    
    //private fields
    //primary constructor
    public JitConfiguration(
      bool showAsmComments,
      bool diffable,
      bool useTieredJit,
      bool usePGO,
      bool runAppMode,
      bool useNoRestoreFlag,
      bool useDotnetPublishForReload,
      bool useDotnetBuildForReload,
      bool useUnloadableContext,
      bool dontGuessTFM,
      [CanBeNull] string selectedCustomJit
    )
    {
      ShowAsmComments = showAsmComments;
      Diffable = diffable;
      UseTieredJit = useTieredJit;
      UsePGO = usePGO;
      RunAppMode = runAppMode;
      UseNoRestoreFlag = useNoRestoreFlag;
      UseDotnetPublishForReload = useDotnetPublishForReload;
      UseDotnetBuildForReload = useDotnetBuildForReload;
      UseUnloadableContext = useUnloadableContext;
      DontGuessTFM = dontGuessTFM;
      SelectedCustomJit = selectedCustomJit;
    }
    //secondary constructor
    //deconstruct trait
    public void Deconstruct(out bool showAsmComments, out bool diffable, out bool useTieredJit, out bool usePGO, out bool runAppMode, out bool useNoRestoreFlag, out bool useDotnetPublishForReload, out bool useDotnetBuildForReload, out bool useUnloadableContext, out bool dontGuessTFM, [CanBeNull] out string selectedCustomJit)
    {
      showAsmComments = ShowAsmComments;
      diffable = Diffable;
      useTieredJit = UseTieredJit;
      usePGO = UsePGO;
      runAppMode = RunAppMode;
      useNoRestoreFlag = UseNoRestoreFlag;
      useDotnetPublishForReload = UseDotnetPublishForReload;
      useDotnetBuildForReload = UseDotnetBuildForReload;
      useUnloadableContext = UseUnloadableContext;
      dontGuessTFM = DontGuessTFM;
      selectedCustomJit = SelectedCustomJit;
    }
    //statics
    
    public static CtxReadDelegate<JitConfiguration> Read = (ctx, reader) => 
    {
      var showAsmComments = reader.ReadBool();
      var diffable = reader.ReadBool();
      var useTieredJit = reader.ReadBool();
      var usePGO = reader.ReadBool();
      var runAppMode = reader.ReadBool();
      var useNoRestoreFlag = reader.ReadBool();
      var useDotnetPublishForReload = reader.ReadBool();
      var useDotnetBuildForReload = reader.ReadBool();
      var useUnloadableContext = reader.ReadBool();
      var dontGuessTFM = reader.ReadBool();
      var selectedCustomJit = ReadStringNullable(ctx, reader);
      var _result = new JitConfiguration(showAsmComments, diffable, useTieredJit, usePGO, runAppMode, useNoRestoreFlag, useDotnetPublishForReload, useDotnetBuildForReload, useUnloadableContext, dontGuessTFM, selectedCustomJit);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static CtxWriteDelegate<JitConfiguration> Write = (ctx, writer, value) => 
    {
      writer.Write(value.ShowAsmComments);
      writer.Write(value.Diffable);
      writer.Write(value.UseTieredJit);
      writer.Write(value.UsePGO);
      writer.Write(value.RunAppMode);
      writer.Write(value.UseNoRestoreFlag);
      writer.Write(value.UseDotnetPublishForReload);
      writer.Write(value.UseDotnetBuildForReload);
      writer.Write(value.UseUnloadableContext);
      writer.Write(value.DontGuessTFM);
      WriteStringNullable(ctx, writer, value.SelectedCustomJit);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    //constants
    
    //custom body
    //methods
    //equals trait
    public override bool Equals(object obj)
    {
      if (ReferenceEquals(null, obj)) return false;
      if (ReferenceEquals(this, obj)) return true;
      if (obj.GetType() != GetType()) return false;
      return Equals((JitConfiguration) obj);
    }
    public bool Equals(JitConfiguration other)
    {
      if (ReferenceEquals(null, other)) return false;
      if (ReferenceEquals(this, other)) return true;
      return ShowAsmComments == other.ShowAsmComments && Diffable == other.Diffable && UseTieredJit == other.UseTieredJit && UsePGO == other.UsePGO && RunAppMode == other.RunAppMode && UseNoRestoreFlag == other.UseNoRestoreFlag && UseDotnetPublishForReload == other.UseDotnetPublishForReload && UseDotnetBuildForReload == other.UseDotnetBuildForReload && UseUnloadableContext == other.UseUnloadableContext && DontGuessTFM == other.DontGuessTFM && Equals(SelectedCustomJit, other.SelectedCustomJit);
    }
    //hash code trait
    public override int GetHashCode()
    {
      unchecked {
        var hash = 0;
        hash = hash * 31 + ShowAsmComments.GetHashCode();
        hash = hash * 31 + Diffable.GetHashCode();
        hash = hash * 31 + UseTieredJit.GetHashCode();
        hash = hash * 31 + UsePGO.GetHashCode();
        hash = hash * 31 + RunAppMode.GetHashCode();
        hash = hash * 31 + UseNoRestoreFlag.GetHashCode();
        hash = hash * 31 + UseDotnetPublishForReload.GetHashCode();
        hash = hash * 31 + UseDotnetBuildForReload.GetHashCode();
        hash = hash * 31 + UseUnloadableContext.GetHashCode();
        hash = hash * 31 + DontGuessTFM.GetHashCode();
        hash = hash * 31 + (SelectedCustomJit != null ? SelectedCustomJit.GetHashCode() : 0);
        return hash;
      }
    }
    //pretty print
    public void Print(PrettyPrinter printer)
    {
      printer.Println("JitConfiguration (");
      using (printer.IndentCookie()) {
        printer.Print("showAsmComments = "); ShowAsmComments.PrintEx(printer); printer.Println();
        printer.Print("diffable = "); Diffable.PrintEx(printer); printer.Println();
        printer.Print("useTieredJit = "); UseTieredJit.PrintEx(printer); printer.Println();
        printer.Print("usePGO = "); UsePGO.PrintEx(printer); printer.Println();
        printer.Print("runAppMode = "); RunAppMode.PrintEx(printer); printer.Println();
        printer.Print("useNoRestoreFlag = "); UseNoRestoreFlag.PrintEx(printer); printer.Println();
        printer.Print("useDotnetPublishForReload = "); UseDotnetPublishForReload.PrintEx(printer); printer.Println();
        printer.Print("useDotnetBuildForReload = "); UseDotnetBuildForReload.PrintEx(printer); printer.Println();
        printer.Print("useUnloadableContext = "); UseUnloadableContext.PrintEx(printer); printer.Println();
        printer.Print("dontGuessTFM = "); DontGuessTFM.PrintEx(printer); printer.Println();
        printer.Print("selectedCustomJit = "); SelectedCustomJit.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
