name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:

  - type: textarea
    id: issue
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or stack trace
      description: |
        Please copy and paste any relevant log output.
        Add the full stack trace if available.
        You can find IDE logs via Help → Collect Logs and Diagnostic Data.

        *This will be automatically formatted into code, so there is no need for backticks.*
      render: shell

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior – provide your build configuration.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: JitAsmViewer Plugin version
      placeholder: 0.1.0
    validations:
      required: true

  - type: input
    id: rider
    attributes:
      label: Rider version
      placeholder: 2025.2
    validations:
      required: true

  - type: input
    id: dotnet
    attributes:
      label: .NET SDK version
      placeholder: 8.0.100
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows

