//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: JitAsmViewerToolWindow.kt:12</p>
  /// </summary>
  [JetBrains.Application.ShellComponent(Application.Parts.Instantiation.DemandAnyThread)]
  public class JitAsmViewerToolWindow : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<JetBrains.Rider.Model.UIAutomation.BeControl> ToolWindowContent => _ToolWindowContent;
    [NotNull] public ISignal<bool> ActivateToolWindow => _ActivateToolWindow;
    
    //private fields
    [NotNull] private readonly RdProperty<JetBrains.Rider.Model.UIAutomation.BeControl> _ToolWindowContent;
    [NotNull] private readonly RdSignal<bool> _ActivateToolWindow;
    
    //primary constructor
    private JitAsmViewerToolWindow(
      [NotNull] RdProperty<JetBrains.Rider.Model.UIAutomation.BeControl> toolWindowContent,
      [NotNull] RdSignal<bool> activateToolWindow
    )
    {
      if (toolWindowContent == null) throw new ArgumentNullException("toolWindowContent");
      if (activateToolWindow == null) throw new ArgumentNullException("activateToolWindow");
      
      _ToolWindowContent = toolWindowContent;
      _ActivateToolWindow = activateToolWindow;
      BindableChildren.Add(new KeyValuePair<string, object>("toolWindowContent", _ToolWindowContent));
      BindableChildren.Add(new KeyValuePair<string, object>("activateToolWindow", _ActivateToolWindow));
    }
    //secondary constructor
    private JitAsmViewerToolWindow (
    ) : this (
      new RdProperty<JetBrains.Rider.Model.UIAutomation.BeControl>(JetBrains.Rider.Model.UIAutomation.BeControl.Read, JetBrains.Rider.Model.UIAutomation.BeControl.Write),
      new RdSignal<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool)
    ) {}
    //deconstruct trait
    //statics
    
    
    
    protected override long SerializationHash => 4211825857250621732L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      serializers.Register(BeJitAsmViewerToolWindowPanel.Read, BeJitAsmViewerToolWindowPanel.Write);
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    public JitAsmViewerToolWindow(Lifetime lifetime, IProtocol protocol) : this()
    {
      Identify(protocol.Identities, RdId.Root.Mix("JitAsmViewerToolWindow"));
      this.BindTopLevel(lifetime, protocol, "JitAsmViewerToolWindow");
    }
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("JitAsmViewerToolWindow (");
      using (printer.IndentCookie()) {
        printer.Print("toolWindowContent = "); _ToolWindowContent.PrintEx(printer); printer.Println();
        printer.Print("activateToolWindow = "); _ActivateToolWindow.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  
  
  /// <summary>
  /// <p>Generated from: JitAsmViewerToolWindow.kt:18</p>
  /// </summary>
  public sealed class BeJitAsmViewerToolWindowPanel : JetBrains.Rider.Model.UIAutomation.BeControl
  {
    //fields
    //public fields
    [NotNull] public IViewableProperty<string> ContentToShow => _ContentToShow;
    
    //private fields
    [NotNull] private readonly RdProperty<string> _ContentToShow;
    
    //primary constructor
    private BeJitAsmViewerToolWindowPanel(
      [NotNull] RdProperty<string> contentToShow,
      [NotNull] RdProperty<bool> enabled,
      [NotNull] RdProperty<string> controlId,
      [NotNull] RdProperty<int> uniqueId,
      [NotNull] RdProperty<int> dataId,
      [NotNull] RdProperty<bool> focusable,
      [NotNull] RdProperty<string> tooltip,
      [NotNull] RdSignal<Unit> focus,
      [NotNull] RdProperty<JetBrains.Rider.Model.UIAutomation.ControlVisibility> visible
    ) : base (
      enabled,
      controlId,
      uniqueId,
      dataId,
      focusable,
      tooltip,
      focus,
      visible
     ) 
    {
      if (contentToShow == null) throw new ArgumentNullException("contentToShow");
      
      _ContentToShow = contentToShow;
      _ContentToShow.OptimizeNested = true;
      _ContentToShow.ValueCanBeNull = true;
      BindableChildren.Add(new KeyValuePair<string, object>("contentToShow", _ContentToShow));
    }
    //secondary constructor
    public BeJitAsmViewerToolWindowPanel (
    ) : this (
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool, true),
      new RdProperty<string>(JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString, ""),
      new RdProperty<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdProperty<int>(JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt),
      new RdProperty<bool>(JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool),
      new RdProperty<string>(ReadStringNullable, WriteStringNullable),
      new RdSignal<Unit>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid),
      new RdProperty<JetBrains.Rider.Model.UIAutomation.ControlVisibility>(ReadControlVisibility, WriteControlVisibility)
    ) {}
    //deconstruct trait
    //statics
    
    public static new CtxReadDelegate<BeJitAsmViewerToolWindowPanel> Read = (ctx, reader) => 
    {
      var _id = RdId.Read(reader);
      var enabled = RdProperty<bool>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool);
      var controlId = RdProperty<string>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadString, JetBrains.Rd.Impl.Serializers.WriteString);
      var uniqueId = RdProperty<int>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt);
      var dataId = RdProperty<int>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadInt, JetBrains.Rd.Impl.Serializers.WriteInt);
      var focusable = RdProperty<bool>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadBool, JetBrains.Rd.Impl.Serializers.WriteBool);
      var tooltip = RdProperty<string>.Read(ctx, reader, ReadStringNullable, WriteStringNullable);
      var focus = RdSignal<Unit>.Read(ctx, reader, JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid);
      var visible = RdProperty<JetBrains.Rider.Model.UIAutomation.ControlVisibility>.Read(ctx, reader, ReadControlVisibility, WriteControlVisibility);
      var contentToShow = RdProperty<string>.Read(ctx, reader, ReadStringNullable, WriteStringNullable);
      var _result = new BeJitAsmViewerToolWindowPanel(contentToShow, enabled, controlId, uniqueId, dataId, focusable, tooltip, focus, visible).WithId(_id);
      return _result;
    };
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    public static CtxReadDelegate<JetBrains.Rider.Model.UIAutomation.ControlVisibility> ReadControlVisibility = new CtxReadDelegate<JetBrains.Rider.Model.UIAutomation.ControlVisibility>(JetBrains.Rd.Impl.Serializers.ReadEnum<JetBrains.Rider.Model.UIAutomation.ControlVisibility>);
    
    public static new CtxWriteDelegate<BeJitAsmViewerToolWindowPanel> Write = (ctx, writer, value) => 
    {
      value.RdId.Write(writer);
      RdProperty<bool>.Write(ctx, writer, value._Enabled);
      RdProperty<string>.Write(ctx, writer, value._ControlId);
      RdProperty<int>.Write(ctx, writer, value._UniqueId);
      RdProperty<int>.Write(ctx, writer, value._DataId);
      RdProperty<bool>.Write(ctx, writer, value._Focusable);
      RdProperty<string>.Write(ctx, writer, value._Tooltip);
      RdSignal<Unit>.Write(ctx, writer, value._Focus);
      RdProperty<JetBrains.Rider.Model.UIAutomation.ControlVisibility>.Write(ctx, writer, value._Visible);
      RdProperty<string>.Write(ctx, writer, value._ContentToShow);
    };
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    public static  CtxWriteDelegate<JetBrains.Rider.Model.UIAutomation.ControlVisibility> WriteControlVisibility = new CtxWriteDelegate<JetBrains.Rider.Model.UIAutomation.ControlVisibility>(JetBrains.Rd.Impl.Serializers.WriteEnum<JetBrains.Rider.Model.UIAutomation.ControlVisibility>);
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("BeJitAsmViewerToolWindowPanel (");
      using (printer.IndentCookie()) {
        printer.Print("contentToShow = "); _ContentToShow.PrintEx(printer); printer.Println();
        printer.Print("enabled = "); _Enabled.PrintEx(printer); printer.Println();
        printer.Print("controlId = "); _ControlId.PrintEx(printer); printer.Println();
        printer.Print("uniqueId = "); _UniqueId.PrintEx(printer); printer.Println();
        printer.Print("dataId = "); _DataId.PrintEx(printer); printer.Println();
        printer.Print("focusable = "); _Focusable.PrintEx(printer); printer.Println();
        printer.Print("tooltip = "); _Tooltip.PrintEx(printer); printer.Println();
        printer.Print("focus = "); _Focus.PrintEx(printer); printer.Println();
        printer.Print("visible = "); _Visible.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
}
