//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a RdGen v1.13.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using JetBrains.Annotations;

using JetBrains.Core;
using JetBrains.Diagnostics;
using JetBrains.Collections;
using JetBrains.Collections.Viewable;
using JetBrains.Lifetimes;
using JetBrains.Serialization;
using JetBrains.Rd;
using JetBrains.Rd.Base;
using JetBrains.Rd.Impl;
using JetBrains.Rd.Tasks;
using JetBrains.Rd.Util;
using JetBrains.Rd.Text;


// ReSharper disable RedundantEmptyObjectCreationArgumentList
// ReSharper disable InconsistentNaming
// ReSharper disable RedundantOverflowCheckingContext


namespace JetBrains.Rider.Model
{
  
  
  /// <summary>
  /// <p>Generated from: JitAsmProviderModel.kt:7</p>
  /// </summary>
  public class JitAsmProviderModel : RdExtBase
  {
    //fields
    //public fields
    [NotNull] public IRdEndpoint<Unit, string> GetJitCodegenForSelectedElement => _GetJitCodegenForSelectedElement;
    
    //private fields
    [NotNull] private readonly RdCall<Unit, string> _GetJitCodegenForSelectedElement;
    
    //primary constructor
    private JitAsmProviderModel(
      [NotNull] RdCall<Unit, string> getJitCodegenForSelectedElement
    )
    {
      if (getJitCodegenForSelectedElement == null) throw new ArgumentNullException("getJitCodegenForSelectedElement");
      
      _GetJitCodegenForSelectedElement = getJitCodegenForSelectedElement;
      _GetJitCodegenForSelectedElement.ValueCanBeNull = true;
      BindableChildren.Add(new KeyValuePair<string, object>("getJitCodegenForSelectedElement", _GetJitCodegenForSelectedElement));
    }
    //secondary constructor
    internal JitAsmProviderModel (
    ) : this (
      new RdCall<Unit, string>(JetBrains.Rd.Impl.Serializers.ReadVoid, JetBrains.Rd.Impl.Serializers.WriteVoid, ReadStringNullable, WriteStringNullable)
    ) {}
    //deconstruct trait
    //statics
    
    public static CtxReadDelegate<string> ReadStringNullable = JetBrains.Rd.Impl.Serializers.ReadString.NullableClass();
    
    public static  CtxWriteDelegate<string> WriteStringNullable = JetBrains.Rd.Impl.Serializers.WriteString.NullableClass();
    
    protected override long SerializationHash => -7815335541907647124L;
    
    protected override Action<ISerializers> Register => RegisterDeclaredTypesSerializers;
    public static void RegisterDeclaredTypesSerializers(ISerializers serializers)
    {
      
      serializers.RegisterToplevelOnce(typeof(IdeRoot), IdeRoot.RegisterDeclaredTypesSerializers);
    }
    
    
    //constants
    
    //custom body
    //methods
    //equals trait
    //hash code trait
    //pretty print
    public override void Print(PrettyPrinter printer)
    {
      printer.Println("JitAsmProviderModel (");
      using (printer.IndentCookie()) {
        printer.Print("getJitCodegenForSelectedElement = "); _GetJitCodegenForSelectedElement.PrintEx(printer); printer.Println();
      }
      printer.Print(")");
    }
    //toString
    public override string ToString()
    {
      var printer = new SingleLinePrettyPrinter();
      Print(printer);
      return printer.ToString();
    }
  }
  public static class SolutionJitAsmProviderModelEx
   {
    public static JitAsmProviderModel GetJitAsmProviderModel(this Solution solution)
    {
      return solution.GetOrCreateExtension("jitAsmProviderModel", () => new JitAsmProviderModel());
    }
  }
}
